/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juniorentreprise;

import java.awt.Dialog.ModalityType;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;



/**
 *
 * @author Arthur
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreConvention.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        //calendrier = new Calendrier(1,1,5,2018,pnlCalend);
        //pnlCalend.add(calendrier);
        JLabel image = new JLabel( new ImageIcon( "images/logoJE.jpg")); 
        add(image);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogConn = new javax.swing.JDialog();
        btnConnexion = new javax.swing.JButton();
        btnAnnulConn = new javax.swing.JButton();
        jXLoginPane = new org.jdesktop.swingx.JXLoginPane();
        btnAdmin = new javax.swing.JButton();
        lblOubli = new javax.swing.JLabel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        dialogInscr = new javax.swing.JDialog();
        pnlInscrLabel = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        lblPaswd = new javax.swing.JLabel();
        pfPaswd = new javax.swing.JPasswordField();
        lblConfirm = new javax.swing.JLabel();
        pfConfirm = new javax.swing.JPasswordField();
        lblJEPrenom = new javax.swing.JLabel();
        tfJEPrenom = new javax.swing.JTextField();
        lblJENom = new javax.swing.JLabel();
        tfJENom = new javax.swing.JTextField();
        lblJEMail = new javax.swing.JLabel();
        tfJEMail = new javax.swing.JTextField();
        lblJETel = new javax.swing.JLabel();
        tfJETel = new javax.swing.JTextField();
        pnlInscrButton = new javax.swing.JPanel();
        btnInscrEnvoyer = new javax.swing.JButton();
        btnInscrAnnul = new javax.swing.JButton();
        btnInscrSuppr = new javax.swing.JButton();
        dialogAjoutEtud = new javax.swing.JDialog();
        pnlAjoutEtudLabel = new javax.swing.JPanel();
        lblAjoutEtudNom = new javax.swing.JLabel();
        tfAjoutEtudNom = new javax.swing.JTextField();
        lblAjoutEtudPrenom = new javax.swing.JLabel();
        tfAjoutEtudPrenom = new javax.swing.JTextField();
        lblAjoutEtudAdresse = new javax.swing.JLabel();
        tfAjoutEtudAdresse = new javax.swing.JTextField();
        lblAjoutEtudCP = new javax.swing.JLabel();
        tfAjoutEtudCP = new javax.swing.JTextField();
        lblAjoutEtudVille = new javax.swing.JLabel();
        tfAjoutEtudVille = new javax.swing.JTextField();
        lblAjoutEtudPays = new javax.swing.JLabel();
        tfAjoutEtudPays = new javax.swing.JTextField();
        lblAjoutEtudMail = new javax.swing.JLabel();
        tfAjoutEtudMail = new javax.swing.JTextField();
        lblAjoutEtudTel = new javax.swing.JLabel();
        tfAjoutEtudTel = new javax.swing.JTextField();
        lblAjoutEtudSexe = new javax.swing.JLabel();
        cbbAjoutEtudSexe = new javax.swing.JComboBox<>();
        lblAjoutEtudNaissance = new javax.swing.JLabel();
        tfAjoutEtudNaissance = new javax.swing.JTextField();
        lblAjoutEtudAnnee = new javax.swing.JLabel();
        spinAjoutEtudAnnee = new javax.swing.JSpinner();
        lblAjoutEtudFormation = new javax.swing.JLabel();
        tfAjoutEtudFormation = new javax.swing.JTextField();
        lblAjoutEtudSS = new javax.swing.JLabel();
        tfAjoutEtudSS = new javax.swing.JTextField();
        plnAjoutEtudButton = new javax.swing.JPanel();
        btnAjoutEtudEnvoyer = new javax.swing.JButton();
        btnAjoutEtudAnnul = new javax.swing.JButton();
        btnAjoutEtudSuppr = new javax.swing.JButton();
        tpOnglets = new javax.swing.JTabbedPane();
        pnlAccueil = new javax.swing.JPanel();
        pnlRappel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taRappel = new javax.swing.JTextArea();
        pnlCalend = new javax.swing.JPanel();
        jXMonthView1 = new org.jdesktop.swingx.JXMonthView();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlEtud = new javax.swing.JPanel();
        spTabEtud = new javax.swing.JScrollPane();
        tabEtud = new javax.swing.JTable();
        spAlphaEtud = new javax.swing.JScrollPane();
        ListAlphaEtud = new javax.swing.JList<>();
        sfEtud = new org.jdesktop.swingx.JXSearchField();
        btnAjoutEtud = new javax.swing.JButton();
        btnSupprEtud = new javax.swing.JButton();
        pnlClient = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabClient = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        pnlProjet = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabProjet = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        pnlDocs = new javax.swing.JPanel();
        btnConvention = new javax.swing.JButton();
        btnIndemnisation = new javax.swing.JButton();
        pnlAside = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        menFichier = new javax.swing.JMenu();
        miNouv = new javax.swing.JMenuItem();
        miOuvr = new javax.swing.JMenuItem();
        miQuit = new javax.swing.JMenuItem();
        menAccueil = new javax.swing.JMenu();
        menPrec = new javax.swing.JMenu();
        menSuiv = new javax.swing.JMenu();
        menConn = new javax.swing.JMenu();
        miConn = new javax.swing.JMenuItem();
        miInscr = new javax.swing.JMenuItem();

        dialogConn.setTitle("Connexion");

        btnConnexion.setText("Connexion");
        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexionActionPerformed(evt);
            }
        });

        btnAnnulConn.setText("Annuler");
        btnAnnulConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulConnActionPerformed(evt);
            }
        });

        jXLoginPane.setToolTipText("");

        btnAdmin.setText("Contacter l'Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        lblOubli.setText("Mot de passe oublié ?");

        javax.swing.GroupLayout dialogConnLayout = new javax.swing.GroupLayout(dialogConn.getContentPane());
        dialogConn.getContentPane().setLayout(dialogConnLayout);
        dialogConnLayout.setHorizontalGroup(
            dialogConnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogConnLayout.createSequentialGroup()
                .addComponent(jXLoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dialogConnLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(dialogConnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogConnLayout.createSequentialGroup()
                        .addComponent(btnConnexion)
                        .addGap(77, 77, 77)
                        .addComponent(btnAnnulConn))
                    .addGroup(dialogConnLayout.createSequentialGroup()
                        .addComponent(lblOubli)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogConnLayout.setVerticalGroup(
            dialogConnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogConnLayout.createSequentialGroup()
                .addComponent(jXLoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogConnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnexion)
                    .addComponent(btnAnnulConn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogConnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin)
                    .addComponent(lblOubli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogInscr.setTitle("Inscription");
        dialogInscr.setModal(true);

        pnlInscrLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInscrLabel.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        lblLogin.setText("Login");
        pnlInscrLabel.add(lblLogin);

        tfLogin.setToolTipText("Username");
        tfLogin.setPreferredSize(new java.awt.Dimension(6, 25));
        pnlInscrLabel.add(tfLogin);

        lblPaswd.setText("Mot de Passe");
        pnlInscrLabel.add(lblPaswd);

        pfPaswd.setToolTipText("8 caractères");
        pnlInscrLabel.add(pfPaswd);

        lblConfirm.setText("Confirmation MdP");
        pnlInscrLabel.add(lblConfirm);

        pfConfirm.setToolTipText("confirmer mdp");
        pnlInscrLabel.add(pfConfirm);

        lblJEPrenom.setText("Prénom");
        pnlInscrLabel.add(lblJEPrenom);
        pnlInscrLabel.add(tfJEPrenom);

        lblJENom.setText("Nom");
        pnlInscrLabel.add(lblJENom);
        pnlInscrLabel.add(tfJENom);

        lblJEMail.setText("Adresse Mail");
        pnlInscrLabel.add(lblJEMail);

        tfJEMail.setToolTipText("abc@mail.com");
        pnlInscrLabel.add(tfJEMail);

        lblJETel.setText("Tel");
        pnlInscrLabel.add(lblJETel);

        tfJETel.setToolTipText("00 00 00 00 00");
        pnlInscrLabel.add(tfJETel);

        btnInscrEnvoyer.setText("Envoyer");
        btnInscrEnvoyer.setToolTipText("Envoyer le formulaire d'inscription");
        btnInscrEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrEnvoyerActionPerformed(evt);
            }
        });

        btnInscrAnnul.setText("Annuler");
        btnInscrAnnul.setToolTipText("Annuler et fermer la fenêtre");
        btnInscrAnnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrAnnulActionPerformed(evt);
            }
        });

        btnInscrSuppr.setText("Supprimer");
        btnInscrSuppr.setToolTipText("Vider tous les champs");
        btnInscrSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscrSupprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInscrButtonLayout = new javax.swing.GroupLayout(pnlInscrButton);
        pnlInscrButton.setLayout(pnlInscrButtonLayout);
        pnlInscrButtonLayout.setHorizontalGroup(
            pnlInscrButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInscrButtonLayout.createSequentialGroup()
                .addComponent(btnInscrEnvoyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnInscrSuppr)
                .addGap(44, 44, 44)
                .addComponent(btnInscrAnnul))
        );
        pnlInscrButtonLayout.setVerticalGroup(
            pnlInscrButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInscrButtonLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlInscrButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscrEnvoyer)
                    .addComponent(btnInscrSuppr)
                    .addComponent(btnInscrAnnul))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogInscrLayout = new javax.swing.GroupLayout(dialogInscr.getContentPane());
        dialogInscr.getContentPane().setLayout(dialogInscrLayout);
        dialogInscrLayout.setHorizontalGroup(
            dialogInscrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInscrLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dialogInscrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInscrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInscrButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dialogInscrLayout.setVerticalGroup(
            dialogInscrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInscrLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlInscrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInscrButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogAjoutEtud.setTitle("Ajouter un étudiant à la BDD");

        pnlAjoutEtudLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remplir les données de l'étudiant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        pnlAjoutEtudLabel.setLayout(new java.awt.GridLayout(13, 2, 10, 10));

        lblAjoutEtudNom.setText("Nom");
        pnlAjoutEtudLabel.add(lblAjoutEtudNom);

        tfAjoutEtudNom.setToolTipText("Username");
        tfAjoutEtudNom.setPreferredSize(new java.awt.Dimension(6, 25));
        pnlAjoutEtudLabel.add(tfAjoutEtudNom);

        lblAjoutEtudPrenom.setText("Prenom");
        pnlAjoutEtudLabel.add(lblAjoutEtudPrenom);

        tfAjoutEtudPrenom.setToolTipText("Username");
        tfAjoutEtudPrenom.setPreferredSize(new java.awt.Dimension(6, 25));
        pnlAjoutEtudLabel.add(tfAjoutEtudPrenom);

        lblAjoutEtudAdresse.setText("Adresse rue");
        pnlAjoutEtudLabel.add(lblAjoutEtudAdresse);

        tfAjoutEtudAdresse.setToolTipText("Username");
        tfAjoutEtudAdresse.setPreferredSize(new java.awt.Dimension(6, 25));
        pnlAjoutEtudLabel.add(tfAjoutEtudAdresse);

        lblAjoutEtudCP.setText("Code Postal");
        pnlAjoutEtudLabel.add(lblAjoutEtudCP);
        pnlAjoutEtudLabel.add(tfAjoutEtudCP);

        lblAjoutEtudVille.setText("Ville");
        pnlAjoutEtudLabel.add(lblAjoutEtudVille);
        pnlAjoutEtudLabel.add(tfAjoutEtudVille);

        lblAjoutEtudPays.setText("Pays");
        pnlAjoutEtudLabel.add(lblAjoutEtudPays);

        tfAjoutEtudPays.setToolTipText("");
        pnlAjoutEtudLabel.add(tfAjoutEtudPays);

        lblAjoutEtudMail.setText("Email");
        pnlAjoutEtudLabel.add(lblAjoutEtudMail);

        tfAjoutEtudMail.setToolTipText("abc@mail.com");
        pnlAjoutEtudLabel.add(tfAjoutEtudMail);

        lblAjoutEtudTel.setText("Telephone");
        pnlAjoutEtudLabel.add(lblAjoutEtudTel);

        tfAjoutEtudTel.setToolTipText("Numéro à 10 chiffres");
        pnlAjoutEtudLabel.add(tfAjoutEtudTel);

        lblAjoutEtudSexe.setText("Sexe");
        pnlAjoutEtudLabel.add(lblAjoutEtudSexe);

        cbbAjoutEtudSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "M", "F" }));
        pnlAjoutEtudLabel.add(cbbAjoutEtudSexe);

        lblAjoutEtudNaissance.setText("Date de naissance");
        pnlAjoutEtudLabel.add(lblAjoutEtudNaissance);

        tfAjoutEtudNaissance.setToolTipText("Format: aaaa-mm-jj");
        pnlAjoutEtudLabel.add(tfAjoutEtudNaissance);

        lblAjoutEtudAnnee.setText("Année de formation");
        pnlAjoutEtudLabel.add(lblAjoutEtudAnnee);

        spinAjoutEtudAnnee.setModel(new javax.swing.SpinnerNumberModel(2018, 1900, 2018, 1));
        pnlAjoutEtudLabel.add(spinAjoutEtudAnnee);

        lblAjoutEtudFormation.setText("Formation");
        pnlAjoutEtudLabel.add(lblAjoutEtudFormation);
        pnlAjoutEtudLabel.add(tfAjoutEtudFormation);

        lblAjoutEtudSS.setText("N° Sécurité Sociale");
        pnlAjoutEtudLabel.add(lblAjoutEtudSS);
        pnlAjoutEtudLabel.add(tfAjoutEtudSS);

        btnAjoutEtudEnvoyer.setText("Envoyer");
        btnAjoutEtudEnvoyer.setToolTipText("Envoyer le formulaire d'inscription");
        btnAjoutEtudEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutEtudEnvoyerActionPerformed(evt);
            }
        });

        btnAjoutEtudAnnul.setText("Annuler");
        btnAjoutEtudAnnul.setToolTipText("Annuler et fermer la fenêtre");
        btnAjoutEtudAnnul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutEtudAnnulActionPerformed(evt);
            }
        });

        btnAjoutEtudSuppr.setText("Supprimer");
        btnAjoutEtudSuppr.setToolTipText("Vider tous les champs");
        btnAjoutEtudSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutEtudSupprActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plnAjoutEtudButtonLayout = new javax.swing.GroupLayout(plnAjoutEtudButton);
        plnAjoutEtudButton.setLayout(plnAjoutEtudButtonLayout);
        plnAjoutEtudButtonLayout.setHorizontalGroup(
            plnAjoutEtudButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnAjoutEtudButtonLayout.createSequentialGroup()
                .addComponent(btnAjoutEtudEnvoyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnAjoutEtudSuppr)
                .addGap(26, 26, 26)
                .addComponent(btnAjoutEtudAnnul))
        );
        plnAjoutEtudButtonLayout.setVerticalGroup(
            plnAjoutEtudButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnAjoutEtudButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(plnAjoutEtudButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutEtudEnvoyer)
                    .addComponent(btnAjoutEtudSuppr)
                    .addComponent(btnAjoutEtudAnnul)))
        );

        javax.swing.GroupLayout dialogAjoutEtudLayout = new javax.swing.GroupLayout(dialogAjoutEtud.getContentPane());
        dialogAjoutEtud.getContentPane().setLayout(dialogAjoutEtudLayout);
        dialogAjoutEtudLayout.setHorizontalGroup(
            dialogAjoutEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAjoutEtudLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dialogAjoutEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAjoutEtudLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plnAjoutEtudButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        dialogAjoutEtudLayout.setVerticalGroup(
            dialogAjoutEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAjoutEtudLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlAjoutEtudLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plnAjoutEtudButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Junior Entreprise");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameJE"); // NOI18N

        pnlRappel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rappels", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        pnlRappel.setToolTipText("");

        taRappel.setColumns(20);
        taRappel.setRows(5);
        jScrollPane4.setViewportView(taRappel);

        javax.swing.GroupLayout pnlRappelLayout = new javax.swing.GroupLayout(pnlRappel);
        pnlRappel.setLayout(pnlRappelLayout);
        pnlRappelLayout.setHorizontalGroup(
            pnlRappelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRappelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        pnlRappelLayout.setVerticalGroup(
            pnlRappelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRappelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCalend.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calendrier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        jXMonthView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXMonthView1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCalendLayout = new javax.swing.GroupLayout(pnlCalend);
        pnlCalend.setLayout(pnlCalendLayout);
        pnlCalendLayout.setHorizontalGroup(
            pnlCalendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, Short.MAX_VALUE)
        );
        pnlCalendLayout.setVerticalGroup(
            pnlCalendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMonthView1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, Short.MAX_VALUE)
        );

        jXImageView1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAccueilLayout = new javax.swing.GroupLayout(pnlAccueil);
        pnlAccueil.setLayout(pnlAccueilLayout);
        pnlAccueilLayout.setHorizontalGroup(
            pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addGroup(pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlCalend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRappel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAccueilLayout.setVerticalGroup(
            pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccueilLayout.createSequentialGroup()
                .addGroup(pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccueilLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccueilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlRappel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCalend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        tpOnglets.addTab("Accueil", pnlAccueil);

        tabEtud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Avatar", "Identifiant", "Nom", "Prénom", "Date inscription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spTabEtud.setViewportView(tabEtud);

        ListAlphaEtud.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        spAlphaEtud.setViewportView(ListAlphaEtud);

        sfEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfEtudActionPerformed(evt);
            }
        });

        btnAjoutEtud.setText("Ajouter");
        btnAjoutEtud.setToolTipText("Ajouter un étudiant");
        btnAjoutEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutEtudActionPerformed(evt);
            }
        });

        btnSupprEtud.setText("Supprimer");
        btnSupprEtud.setToolTipText("Supprimer un étudiant");
        btnSupprEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprEtudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEtudLayout = new javax.swing.GroupLayout(pnlEtud);
        pnlEtud.setLayout(pnlEtudLayout);
        pnlEtudLayout.setHorizontalGroup(
            pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEtudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEtudLayout.createSequentialGroup()
                        .addGroup(pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sfEtud, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                            .addComponent(spTabEtud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spAlphaEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEtudLayout.createSequentialGroup()
                        .addComponent(btnAjoutEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnSupprEtud)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEtudLayout.setVerticalGroup(
            pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEtudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEtudLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(spAlphaEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEtudLayout.createSequentialGroup()
                        .addComponent(sfEtud, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlEtudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjoutEtud)
                            .addComponent(btnSupprEtud))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTabEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tpOnglets.addTab("Etudiants", pnlEtud);

        tabClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Avatar", "Identifiant", "Nom", "Prénom", "Date inscription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabClient);

        jTextField3.setText("Barre de recherche (à réaliser)");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList2);

        javax.swing.GroupLayout pnlClientLayout = new javax.swing.GroupLayout(pnlClient);
        pnlClient.setLayout(pnlClientLayout);
        pnlClientLayout.setHorizontalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlClientLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlClientLayout.setVerticalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        tpOnglets.addTab("Clients", pnlClient);

        tabProjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Avatar", "Identifiant", "Nom", "Prénom", "Date inscription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tabProjet);

        jTextField4.setText("Barre de recherche (à réaliser)");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList3);

        javax.swing.GroupLayout pnlProjetLayout = new javax.swing.GroupLayout(pnlProjet);
        pnlProjet.setLayout(pnlProjetLayout);
        pnlProjetLayout.setHorizontalGroup(
            pnlProjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProjetLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlProjetLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlProjetLayout.setVerticalGroup(
            pnlProjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProjetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );

        tpOnglets.addTab("Projets", pnlProjet);

        btnConvention.setText("Créer Convention");
        btnConvention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConventionActionPerformed(evt);
            }
        });

        btnIndemnisation.setText("Gérer Indemnisations");
        btnIndemnisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndemnisationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDocsLayout = new javax.swing.GroupLayout(pnlDocs);
        pnlDocs.setLayout(pnlDocsLayout);
        pnlDocsLayout.setHorizontalGroup(
            pnlDocsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocsLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnConvention)
                .addGap(127, 127, 127)
                .addComponent(btnIndemnisation)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        pnlDocsLayout.setVerticalGroup(
            pnlDocsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocsLayout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addGroup(pnlDocsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvention)
                    .addComponent(btnIndemnisation))
                .addGap(59, 59, 59))
        );

        tpOnglets.addTab("Documents", pnlDocs);

        jToggleButton1.setText("ON");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAsideLayout = new javax.swing.GroupLayout(pnlAside);
        pnlAside.setLayout(pnlAsideLayout);
        pnlAsideLayout.setHorizontalGroup(
            pnlAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAsideLayout.setVerticalGroup(
            pnlAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menFichier.setText("Fichier");

        miNouv.setText("Nouveau");
        menFichier.add(miNouv);

        miOuvr.setText("Ouvrir");
        menFichier.add(miOuvr);

        miQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miQuit.setText("Quitter");
        miQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuitActionPerformed(evt);
            }
        });
        menFichier.add(miQuit);

        menuBar.add(menFichier);

        menAccueil.setText("Accueil");
        menAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAccueilActionPerformed(evt);
            }
        });
        menuBar.add(menAccueil);

        menPrec.setText("Précédent (<)");
        menuBar.add(menPrec);

        menSuiv.setText("(>) Suivant");
        menuBar.add(menSuiv);

        menConn.setText("Connexion");

        miConn.setText("Se connecter");
        miConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConnActionPerformed(evt);
            }
        });
        menConn.add(miConn);

        miInscr.setText("S'inscrire");
        miInscr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInscrActionPerformed(evt);
            }
        });
        menConn.add(miInscr);

        menuBar.add(menConn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(tpOnglets))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpOnglets)
            .addComponent(pnlAside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miInscrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInscrActionPerformed
        try { 
            dialogInscr.setModalityType(ModalityType.APPLICATION_MODAL);
            dialogInscr.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialogInscr.pack();
            dialogInscr.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_miInscrActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void miConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConnActionPerformed
        try { 
            dialogConn.setModalityType(ModalityType.APPLICATION_MODAL);
            dialogConn.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialogConn.pack();
            dialogConn.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_miConnActionPerformed

    private void menAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAccueilActionPerformed
        tpOnglets.setSelectedIndex(0);
    }//GEN-LAST:event_menAccueilActionPerformed

    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        Connection connexion = null;
        Statement statement = null;
        ResultSet resultat = null;
        try {
            //Ouverture de la connexion, initialisation d'un Statement, initialisation d'un ResultSet, etc.
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://iutdoua-web.univ-lyon1.fr:3306/p1702775", "p1702775", "296054");
            Statement stmt=(Statement)con.createStatement();
            String nomCon = jXLoginPane.getUserName();
            String passCon = String.valueOf(jXLoginPane.getPassword());
            String request = "SELECT * FROM MembreJE WHERE login='"+nomCon+"' AND password='"+passCon+"';";
            
            /* Exécution d'une requête de lecture */
            resultat =  stmt.executeQuery(request);//query pour des requetes SELECT
            if(resultat.next())
            {
                int idUtilisateur = resultat.getInt( "id" );
                String emailUtilisateur = resultat.getString( "email" );
                String motDePasseUtilisateur = resultat.getString( "password" );
                String nomUtilisateur = resultat.getString( "nom" );
                System.out.println("Données retournées par la requête : id = " + idUtilisateur + ", email = " + emailUtilisateur
                    + ", motdepasse = "
                    + motDePasseUtilisateur + ", nom = " + nomUtilisateur + "." );
                JOptionPane.showMessageDialog(null, "Connexion réussie !" ,"Connexion", 1);
            }
            else{
                JOptionPane.showMessageDialog(null, "Identifiants invalides" ,"Erreur", 1);
            }

            /* Traiter ici les valeurs récupérées. */
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);
        } finally {
            if ( resultat != null ) {
                try {
                    /* On commence par fermer le ResultSet */
                    resultat.close();
                } catch ( SQLException ignore ) {
                    JOptionPane.showMessageDialog(null, ignore.getMessage() ,"Error", 1);
                }
            }
            if ( statement != null ) {
                try {
                    /* Puis on ferme le Statement */
                    statement.close();
                } catch ( SQLException ignore ) {
                    JOptionPane.showMessageDialog(null, ignore.getMessage() ,"Error", 1);
                }
            }
            if ( connexion != null ) {
                try {
                    /* Et enfin on ferme la connexion */
                    connexion.close();
                } catch ( SQLException ignore ) {
                    JOptionPane.showMessageDialog(null, ignore.getMessage() ,"Error", 1);
                }
            }
        }
    }//GEN-LAST:event_btnConnexionActionPerformed

    private void btnAnnulConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulConnActionPerformed
        dialogConn.dispose();
    }//GEN-LAST:event_btnAnnulConnActionPerformed

    private void btnConventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConventionActionPerformed
        try {
            FenetreConvention convention = new FenetreConvention();
            convention.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            convention.pack();
            convention.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnConventionActionPerformed

    private void sfEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfEtudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfEtudActionPerformed

    private void miQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuitActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment quitter ?","Fenêtre de Confirmation" , YES_NO_CANCEL_OPTION);
        //Si on répond "Oui", on quitte.
        if (response==JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_miQuitActionPerformed


    private void jXMonthView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXMonthView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXMonthView1ActionPerformed

    private void btnInscrSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrSupprActionPerformed
        //On vide les champs de texte
        tfLogin.setText("");
        tfJEMail.setText("");
        pfPaswd.setText("");
        pfConfirm.setText("");
        tfJENom.setText("");
        tfJEPrenom.setText("");
        tfJETel.setText("");
    }//GEN-LAST:event_btnInscrSupprActionPerformed

    private void btnInscrAnnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrAnnulActionPerformed
        dialogInscr.dispose();
    }//GEN-LAST:event_btnInscrAnnulActionPerformed

    private void btnInscrEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscrEnvoyerActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://iutdoua-web.univ-lyon1.fr:3306/p1702775", "p1702775", "296054");
            Statement stmt=(Statement)con.createStatement();

            String defautPosteJE = "Membre";
            String myPass = String.valueOf(pfPaswd.getPassword());
            String myConfirm = String.valueOf(pfConfirm.getPassword());
            String myLogin = tfLogin.getText();
            String myNom = tfJENom.getText();
            String myPrenom = tfJEPrenom.getText();
            String myMail = tfJEMail.getText();
            String myTel = tfJETel.getText();
            if(!myLogin.equals("") && !myPass.equals("") && myPass.equals(myConfirm) && !myNom.equals("") && !myPrenom.equals("") &&
                !myMail.equals("") && !myTel.equals("") && myMail.matches("^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)+$"))
            {
                String insert="INSERT INTO MembreJE (Nom,Prenom,Email,Tel,Poste,Login,Password) VALUES('"+ tfJENom.getText() +"','"+ tfJEPrenom.getText() +"','"+ tfJEMail.getText()
                +"','"+ tfJETel.getText() +"','"+ defautPosteJE +"','"+ tfLogin.getText() +"','"+ myPass +"');";
                stmt.executeUpdate(insert);//update pour des requetes INSERT, UPDATE, DELETE
                JOptionPane.showMessageDialog(null, "Inscription réussie" ,"Inscription", 1);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Erreur" ,"Error", 1);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Error", 1);

        }
    }//GEN-LAST:event_btnInscrEnvoyerActionPerformed

    private void btnIndemnisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndemnisationActionPerformed
        try {
            FenetreIndemnisation indemnisation = new FenetreIndemnisation();
            indemnisation.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            indemnisation.pack();
            indemnisation.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnIndemnisationActionPerformed


    private void btnAjoutEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutEtudActionPerformed
        try { 
            dialogAjoutEtud.setModalityType(ModalityType.APPLICATION_MODAL);
            dialogAjoutEtud.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialogAjoutEtud.pack();
            dialogAjoutEtud.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAjoutEtudActionPerformed

    private void btnAjoutEtudSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutEtudSupprActionPerformed
        tfAjoutEtudNom.setText("");
        tfAjoutEtudPrenom.setText("");
        tfAjoutEtudAdresse.setText("");
        tfAjoutEtudCP.setText("");
        tfAjoutEtudVille.setText("");
        tfAjoutEtudPays.setText("");
        tfAjoutEtudMail.setText("");
        tfAjoutEtudTel.setText("");
        cbbAjoutEtudSexe.setSelectedItem("");
        tfAjoutEtudNaissance.setText("");
        spinAjoutEtudAnnee.setValue(2018);
        tfAjoutEtudFormation.setText("");
        tfAjoutEtudSS.setText("");
    }//GEN-LAST:event_btnAjoutEtudSupprActionPerformed

    private void btnAjoutEtudAnnulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutEtudAnnulActionPerformed
        dialogAjoutEtud.dispose();
    }//GEN-LAST:event_btnAjoutEtudAnnulActionPerformed

    private void btnAjoutEtudEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutEtudEnvoyerActionPerformed
        Connection con = null; // connection reference variable for getting
        // connection
        Statement stmt = null; // Statement reference variable for query
        // Execution
        ResultSet rs = null; // ResultSet reference variable for saving query
        // result 
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://iutdoua-web.univ-lyon1.fr:3306/p1702775", "p1702775", "296054");
            stmt= con.createStatement();

            String EtuNom = tfAjoutEtudNom.getText();
            String EtuPrenom = tfAjoutEtudPrenom.getText();
            String EtuAdresse = tfAjoutEtudAdresse.getText();
            String EtuCP = tfAjoutEtudCP.getText();
            String EtuVille = tfAjoutEtudVille.getText();
            String EtuPays = tfAjoutEtudPays.getText();
            String EtuMail = tfAjoutEtudMail.getText();
            String EtuTel = tfAjoutEtudTel.getText();
            String EtuSexe = cbbAjoutEtudSexe.getSelectedItem().toString();
            String EtuNaissance = tfAjoutEtudNaissance.getText();
            String EtuAnnee = spinAjoutEtudAnnee.getValue().toString();
            String EtuFormation = tfAjoutEtudFormation.getText();
            String EtuNumSS = tfAjoutEtudSS.getText();
            
            if(!EtuNom.equals("") && !EtuPrenom.equals("") && !EtuAdresse.equals("") && !EtuCP.equals("") &&
                !EtuVille.equals("") && !EtuPays.equals("") && !EtuMail.equals("") && EtuMail.matches("^[_a-z0-9-]+(\\.[_a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)+$")
                && !EtuTel.equals("") && EtuTel.matches("^0[1-9][0-9]{8}$") && !EtuSexe.equals("") && !EtuNaissance.equals("") && !EtuAnnee.equals("") && !EtuFormation.equals("") 
                && !EtuNumSS.equals("") //&& EtuNumSS.matches("^[1-3][0-9]{4}(2[AB]|[0-9]{2})[0-9]{6}$")
               )
            {
                String insert="INSERT INTO Etudiant (NomEtudiant,Prenom,Adresse,CodePostal,Ville,Pays,Email,Telephone,Sexe,DateNaissance,AnneeFormation,Formation, NumSS) VALUES('"+ EtuNom +"','"+ EtuPrenom +"','"+ EtuAdresse +"','"+ EtuCP +"','"+ EtuVille +"','"
                        + EtuPays +"','"+ EtuMail +"','"+ EtuTel +"','"+ EtuSexe +"','"+ EtuNaissance +"','"+ EtuAnnee +"','"+ EtuFormation +"','"+ EtuNumSS +"');";
                stmt.executeUpdate(insert);//update pour des requetes INSERT, UPDATE, DELETE
                JOptionPane.showMessageDialog(null, "Ajout de l'étudiant à la base de données réussi" ,"Ajout d'un étudiant", 1);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Il faut remplir tous les champs correctement" ,"Erreur", 3);
            }

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Erreur Ajout", 3);

        }
    }//GEN-LAST:event_btnAjoutEtudEnvoyerActionPerformed

    private void btnSupprEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprEtudActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://iutdoua-web.univ-lyon1.fr:3306/p1702775", "p1702775", "296054");
            Statement stmt=(Statement)con.createStatement();
            //On vérifie que l'utilisateur à sélectionné une ligne
            if(tabEtud.getSelectedRow()==-1)
            {
                //Si il n'y a pa de lignes selectionnées, on affiche un warning
                JOptionPane.showMessageDialog(this, "Selectionnez d'abord la ou les lignes à supprimer" ,"Erreur", 2);
            }else{
                //Tant qu'il y a des lignes selectionnées, on les supprime
                
                while(tabEtud.getSelectedRow()!=-1){ //getSelectedRow() retourne -1 si rien n'est sélectionné
                    String delete = "DELETE FROM ETUDIANT WHERE IDETUDIANT="+tabEtud.getSelectedRow()+";";
                    stmt.executeUpdate(delete);
                }
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() ,"Erreur Supprimer", 3);

        }
    }//GEN-LAST:event_btnSupprEtudActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed



    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListAlphaEtud;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAjoutEtud;
    private javax.swing.JButton btnAjoutEtudAnnul;
    private javax.swing.JButton btnAjoutEtudEnvoyer;
    private javax.swing.JButton btnAjoutEtudSuppr;
    private javax.swing.JButton btnAnnulConn;
    private javax.swing.JButton btnConnexion;
    private javax.swing.JButton btnConvention;
    private javax.swing.JButton btnIndemnisation;
    private javax.swing.JButton btnInscrAnnul;
    private javax.swing.JButton btnInscrEnvoyer;
    private javax.swing.JButton btnInscrSuppr;
    private javax.swing.JButton btnSupprEtud;
    private javax.swing.JComboBox<String> cbbAjoutEtudSexe;
    private javax.swing.JDialog dialogAjoutEtud;
    private javax.swing.JDialog dialogConn;
    private javax.swing.JDialog dialogInscr;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private org.jdesktop.swingx.JXLoginPane jXLoginPane;
    private org.jdesktop.swingx.JXMonthView jXMonthView1;
    private javax.swing.JLabel lblAjoutEtudAdresse;
    private javax.swing.JLabel lblAjoutEtudAnnee;
    private javax.swing.JLabel lblAjoutEtudCP;
    private javax.swing.JLabel lblAjoutEtudFormation;
    private javax.swing.JLabel lblAjoutEtudMail;
    private javax.swing.JLabel lblAjoutEtudNaissance;
    private javax.swing.JLabel lblAjoutEtudNom;
    private javax.swing.JLabel lblAjoutEtudPays;
    private javax.swing.JLabel lblAjoutEtudPrenom;
    private javax.swing.JLabel lblAjoutEtudSS;
    private javax.swing.JLabel lblAjoutEtudSexe;
    private javax.swing.JLabel lblAjoutEtudTel;
    private javax.swing.JLabel lblAjoutEtudVille;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblJEMail;
    private javax.swing.JLabel lblJENom;
    private javax.swing.JLabel lblJEPrenom;
    private javax.swing.JLabel lblJETel;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblOubli;
    private javax.swing.JLabel lblPaswd;
    private javax.swing.JMenu menAccueil;
    private javax.swing.JMenu menConn;
    private javax.swing.JMenu menFichier;
    private javax.swing.JMenu menPrec;
    private javax.swing.JMenu menSuiv;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miConn;
    private javax.swing.JMenuItem miInscr;
    private javax.swing.JMenuItem miNouv;
    private javax.swing.JMenuItem miOuvr;
    private javax.swing.JMenuItem miQuit;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfPaswd;
    private javax.swing.JPanel plnAjoutEtudButton;
    private javax.swing.JPanel pnlAccueil;
    private javax.swing.JPanel pnlAjoutEtudLabel;
    private javax.swing.JPanel pnlAside;
    private javax.swing.JPanel pnlCalend;
    private javax.swing.JPanel pnlClient;
    private javax.swing.JPanel pnlDocs;
    private javax.swing.JPanel pnlEtud;
    private javax.swing.JPanel pnlInscrButton;
    private javax.swing.JPanel pnlInscrLabel;
    private javax.swing.JPanel pnlProjet;
    private javax.swing.JPanel pnlRappel;
    private org.jdesktop.swingx.JXSearchField sfEtud;
    private javax.swing.JScrollPane spAlphaEtud;
    private javax.swing.JScrollPane spTabEtud;
    private javax.swing.JSpinner spinAjoutEtudAnnee;
    private javax.swing.JTextArea taRappel;
    private javax.swing.JTable tabClient;
    private javax.swing.JTable tabEtud;
    private javax.swing.JTable tabProjet;
    private javax.swing.JTextField tfAjoutEtudAdresse;
    private javax.swing.JTextField tfAjoutEtudCP;
    private javax.swing.JTextField tfAjoutEtudFormation;
    private javax.swing.JTextField tfAjoutEtudMail;
    private javax.swing.JTextField tfAjoutEtudNaissance;
    private javax.swing.JTextField tfAjoutEtudNom;
    private javax.swing.JTextField tfAjoutEtudPays;
    private javax.swing.JTextField tfAjoutEtudPrenom;
    private javax.swing.JTextField tfAjoutEtudSS;
    private javax.swing.JTextField tfAjoutEtudTel;
    private javax.swing.JTextField tfAjoutEtudVille;
    private javax.swing.JTextField tfJEMail;
    private javax.swing.JTextField tfJENom;
    private javax.swing.JTextField tfJEPrenom;
    private javax.swing.JTextField tfJETel;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTabbedPane tpOnglets;
    // End of variables declaration//GEN-END:variables

}
